config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope 'private' do
    resources :messages, only: [:index, :new, :create], :as => 'private_messages'
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :job_vacancies
  resources :applicants

  get '/search' => 'searches#search', as: :search
  get '/autocomplete/:query' => 'searches#autocomplete', as: :autocomplete

  get '/publications' => 'publications#index', as: :publications

  root 'users#home'
  post   '/sign_up'  => 'users#sign_up',  as: :sign_up
  post   '/sign_in'  => 'users#sign_in',  as: :sign_in
  delete '/sign_out' => 'users#sign_out', as: :sign_out
  get    '/:name'    => 'users#profile',  as: :profile
  post '/upload_photo' => 'users#upload_photo', as: :upload_photo
  post '/upload_cover' => 'users#upload_cover', as: :upload_cover

  post   '/new_post' => 'posts#create',   as: :new_post

  post   '/follow'   => 'relationships#create', as: :follow
  delete '/unfollow' => 'relationships#destroy', as: :unfollow

  resources :resumes

end

app/models/job_vacancy.rb
class JobVacancy < ActiveRecord::Base
  belongs_to :user
  has_many :applicants
end

app/controllers/job_vacancies_controller.rb
class JobVacanciesController < ApplicationController
  def index
    @job_vacancies = JobVacancy.all
  end

  def new
    @job_vacancy = JobVacancy.new
  end

  def create
    # render(:text => params)
    @job_vacancy = JobVacancy.new(job_vacancy_params)
    @job_vacancy.user = current_user
    @job_vacancy.save
    redirect_to @job_vacancy
  end

  def show
    # render(:text => params)
    @job_vacancy = JobVacancy.find(params[:id])
  end

  def edit
    # render(:text => params)
    @job_vacancy = JobVacancy.find(params[:id])
  end

  def update
    # render(:text => params)
    @job_vacancy = JobVacancy.find(params[:id])
    @job_vacancy.update(job_vacancy_params)
    redirect_to @job_vacancy
  end

  def destroy
    # render(:text => params)
    @job_vacancy = JobVacancy.find(params[:id])
    @job_vacancy.destroy
    redirect_to job_vacancies_url
  end

  private
  def job_vacancy_params
    params.require(:job_vacancy).permit(:years_of_experience, :education)
  end
end

app/helpers/job_vacancies_helper.rb
module JobVacanciesHelper
end

app/views/job_vacancies/edit.html.erb
<div class="container">
  <%= form_for @job_vacancy do |f| %>
      <div class="row">
        <div class="col-md-3">
          <%= f.label :years_of_experience, 'Años de experiencia' %>
          <%= f.number_field :years_of_experience, class: 'form-control' %>
          <%= f.label :education, 'Educación' %>
          <%= f.text_field :education, class: 'form-control' %>
          <%= f.submit 'Actualizar informacion', class: 'btn btn-primary' %>
        </div>
      </div>
  <% end %>
</div>

app/views/job_vacancies/index.html.erb
<style>
  .fila-vacantes{
      padding: 5px;
  }
  .contenedor-vacantes{
      background-color: white;
      padding: 15px;
      margin-top: 15px;
      border-radius: 8px;
  }
</style>
<div class="container">
  <div class="row ">
    <div class="col-md-9  contenedor-vacantes">
      <div class="row fila-vacantes">
        <div class="col-md-4"><h4>PERSONAL REQUERIDO</h4></div>
        <div class="col-md-4"><h4>EXPERIENCIA</h4></div>
        <div class="col-md-4"></div>
      </div>
      <% @job_vacancies.each do |vacancy| %>
          <div class="row fila-vacantes">
            <div class="col-md-4"><p><%= vacancy.education %></p></div>
            <div class="col-md-2"><%= vacancy.years_of_experience %></div>
            <div class="col-md-2"><%= link_to 'EDITAR', edit_job_vacancy_path(vacancy.id), class: 'btn btn-success btn-block' %></div>
            <div class="col-md-2"><%= link_to 'MOSTRAR', job_vacancy_path(vacancy.id), class: 'btn btn-success btn-block' %></div>
            <div class="col-md-2"><%= link_to 'ELIMINAR', job_vacancy_path(vacancy.id), method: :delete,  class: 'btn btn-danger btn-block' %></div>
          </div>
          <hr>
      <% end %>
      <%= link_to 'Contratar', new_job_vacancy_path, class: 'btn btn-primary' %>

    </div>
    <div class="col-md-3">
   </div>
  </div>
</div>

app/views/job_vacancies/new.html.erb
<div class="container">
  <%= form_for @job_vacancy do |f| %>
      <div class="row">
        <div class="col-md-3">
          <%= f.label :years_of_experience, 'Años de experiencia' %>
          <%= f.number_field :years_of_experience, class: 'form-control' %>
          <%= f.label :education, 'Educación' %>
          <%= f.text_field :education, class: 'form-control' %>
          <%= f.submit 'Ofertar empleo', class: 'btn btn-primary' %>
        </div>
      </div>
  <% end %>
    <%= link_to 'Atras', job_vacancies_path%>
</div>

app/views/job_vacancies/show.html.erb
<div class="container">
  <strong>Experiencia:</strong>
  <%= @job_vacancy.years_of_experience %> <br>
  <strong>Formación:</strong>
  <%= @job_vacancy.education %> <br>
  <% if current_user.id == @job_vacancy.user_id  %>
      <%= link_to 'Editar', edit_job_vacancy_path(@job_vacancy) %> |
      <%= link_to 'Lista de ofertados', job_vacancies_path %>  <br>
  <% end %>
  <% if current_user.id != @job_vacancy.user_id %>
      <% if Applicant.not_applied?(@job_vacancy.id, current_user.id) %>
          <%= form_for Applicant.new do |f| %>
              <%= f.hidden_field :job_vacancy_id, value: @job_vacancy.id %>
              <%= f.submit 'Aplicar'%>
          <% end %>
      <% end %>
  <% end %>
</div>