config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope 'private' do
    resources :messages, only: [:index, :new, :create], :as => 'private_messages'
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :job_vacancies
  resources :applicants

  get '/search' => 'searches#search', as: :search
  get '/autocomplete/:query' => 'searches#autocomplete', as: :autocomplete

  get '/publications' => 'publications#index', as: :publications

  root 'users#home'
  post   '/sign_up'  => 'users#sign_up',  as: :sign_up
  post   '/sign_in'  => 'users#sign_in',  as: :sign_in
  delete '/sign_out' => 'users#sign_out', as: :sign_out
  get    '/:name'    => 'users#profile',  as: :profile
  post '/upload_photo' => 'users#upload_photo', as: :upload_photo
  post '/upload_cover' => 'users#upload_cover', as: :upload_cover

  post   '/new_post' => 'posts#create',   as: :new_post

  post   '/follow'   => 'relationships#create', as: :follow
  delete '/unfollow' => 'relationships#destroy', as: :unfollow

  resources :resumes

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :get_mailbox
  before_action :get_conversation, except: [:index, :empty_trash]
  before_action :get_box, only: [:index]

  def index
    if @box.eql? 'bandeja'
      @conversations = @mailbox.inbox
    elsif @box.eql? 'enviados'
      @conversations = @mailbox.sentbox
    else
      @conversations = @mailbox.trash
    end
    @conversations = @conversations.paginate(page: params[:page], per_page: 5)
  end

  def show
    # render(:text => params)
    @conversation.mark_as_read(current_user)
    respond_to do |format|
      format.js{}
      format.html{}
    end
  end

  def reply
    # render(:text => params)
    var = @conversation
    current_user.reply_to_conversation(@conversation, params[:body])
    redirect_to conversations_path
  end
  def destroy
    @conversation.move_to_trash(current_user)
    flash[:success] = 'The conversation was moved to trash.'
    # redirect_to conversations_path
    redirect_to :back
  end
  def restore
    @conversation.untrash(current_user)
    flash[:success] = 'The conversation was restored.'
    # redirect_to conversations_path
    redirect_to :back
  end
  def empty_trash
    @mailbox.trash.each do |conversation|
      conversation.receipts_for(current_user).update_all(deleted: true)
    end
    flash[:success] = 'Your trash was cleaned!'
    redirect_to conversations_path
  end

  private
  def get_mailbox
    @mailbox ||= current_user.mailbox
  end

  def get_conversation
    @conversation ||= @mailbox.conversations.find(params[:id])
  end

  def get_box
    if params[:box].blank? or !['bandeja', 'enviados', 'papelera', 'componer'].include?(params[:box])
      params[:box] = 'bandeja'
    end
    @box = params[:box]
  end


end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def mailbox_section(title, current_box, icon, opts = {})
    opts[:class] = opts.fetch(:class, '')
    opts[:class] += '-mailbox-active' if title.downcase == current_box
    (content_tag :li, link_to(raw(icon+' '+title.capitalize), conversations_path(box: title.downcase)), opts)
  end
end

app/views/conversations/_conversation.html.erb
<li class="list-group-item clearfix email-item">
  <div class="row">

    <div class="col-md-7">
      <% if @box == 'bandeja' %>
        <% if current_user.active_participants(conversation).count == 1 %>
          <% if conversation.is_unread?(current_user)%>
              <span class="glyphicon glyphicon-envelope is_unread"></span>
          <% else %>
              <span class="glyphicon glyphicon-inbox is_read"></span>
          <% end %>
          <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
          <%= current_user.active_participants(conversation)[0].name %>
        <% end %>
        <% if current_user.active_participants(conversation).count == 2 %>
          <% if conversation.is_unread?(current_user)%>
            <span class="glyphicon glyphicon-envelope is_unread"></span>
          <% else %>
            <span class="glyphicon glyphicon-inbox is_read"></span>
          <% end %>
          <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
          <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
          <%= current_user.active_participants(conversation)[0].name %>,
          <%= current_user.active_participants(conversation)[1].name %>
        <% end %>
        <% if current_user.active_participants(conversation).count == 3 %>
          <% if conversation.is_unread?(current_user)%>
            <span class="glyphicon glyphicon-envelope is_unread"></span>
          <% else %>
            <span class="glyphicon glyphicon-inbox is_read"></span>
          <% end %>
          <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
          <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
          <%= image_tag current_user.active_participants(conversation)[2].avatar.url, class: 'img-participant img-participant-third center-block' %>
          <%= current_user.active_participants(conversation)[0].name %>,
          <%= current_user.active_participants(conversation)[1].name %>,
          <%= current_user.active_participants(conversation)[2].name %>
        <% end %>
        <% if current_user.active_participants(conversation).count > 3 %>
          <% if conversation.is_unread?(current_user)%>
            <span class="glyphicon glyphicon-envelope is_unread"></span>
          <% else %>
            <span class="glyphicon glyphicon-inbox is_read"></span>
          <% end %>
            <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
            <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
            <span class="img-participant-others">+<%= current_user.active_participants(conversation).count-2 %></span>
            <%= current_user.active_participants(conversation)[0].name %>,
            <%= current_user.active_participants(conversation)[1].name %>,
            Otros
        <% end %>
      <% end %>

      <% if @box == 'enviados' %>
          <% if conversation.participants.count == 2 %>
              <span class="glyphicon glyphicon-send is_send"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>
          <% end %>
          <% if conversation.participants.count  == 3 %>
              <span class="glyphicon glyphicon-send is_send"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>
          <% end %>
          <% if conversation.participants.count  == 4 %>
              <span class="glyphicon glyphicon-send is_send"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[2].avatar.url), class: 'img-participant img-participant-third center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>,
              <%= (conversation.participants - [conversation.originator])[2].name %>
          <% end %>
          <% if conversation.participants.count   > 4 %>
              <span class="glyphicon glyphicon-send is_send"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <span class="img-participant-others">+<%= (conversation.participants - [conversation.originator]).count-2 %></span>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>,
              Otros
          <% end %>
      <% end %>
      <% if @box == 'papelera' %>
          <% if conversation.participants.count == 2 %>
              <span class="glyphicon glyphicon-trash is_trashed"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>
          <% end %>
          <% if conversation.participants.count  == 3 %>
              <span class="glyphicon glyphicon-trash is_trashed"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>
          <% end %>
          <% if conversation.participants.count  == 4 %>
              <span class="glyphicon glyphicon-trash is_trashed"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[2].avatar.url), class: 'img-participant img-participant-third center-block' %>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>,
              <%= (conversation.participants - [conversation.originator])[2].name %>
          <% end %>
          <% if conversation.participants.count   > 4 %>
              <span class="glyphicon glyphicon-trash is_trashed"></span>
              <%= image_tag ((conversation.participants - [conversation.originator])[0].avatar.url), class: 'img-participant img-participant-first center-block' %>
              <%= image_tag ((conversation.participants - [conversation.originator])[1].avatar.url), class: 'img-participant img-participant-second center-block' %>
              <span class="img-participant-others">+<%= (conversation.participants - [conversation.originator]).count-2 %></span>
              <%= (conversation.participants - [conversation.originator])[0].name %>,
              <%= (conversation.participants - [conversation.originator])[1].name %>,
              Otros
          <% end %>
      <% end %>

    </div>

    <!--<div class="col-md-2 fix-vertical-align"><%= link_to conversation.subject, conversation_path(conversation) %></div>-->
    <div class="col-md-2 fix-vertical-align"><%= link_to conversation.subject, conversation_path(conversation), remote: true, class: 'subject' %></div>
    <div class="col-md-2 fix-vertical-align"><%= conversation.created_at.strftime('%-d %B %Y') %></div>
    <div class="col-md-1  fix-vertical-align">
      <div class="btn-group-vertical">
        <% if conversation.is_trashed?(current_user) %>
            <%= link_to '<i class="fa fa-reply icon-restore"></i><span class="glyphicon glyphicon-trash icon-restore"></span>'.html_safe, restore_conversation_path(conversation), method: :post %>
        <% else %>
            <%= link_to '<span class="glyphicon glyphicon-trash"></span>'.html_safe, conversation_path(conversation), method: :delete, data: {confirm: 'Are you sure?'}, class: 'icon-trash'%>
        <% end %>
      </div>

    </div>

  </div>
</li>

app/views/conversations/_form.html.erb
<%= form_tag private_messages_path, remote: :true, method: :post, id:'send-msg' do %>
    <div class="form-group form-msg">
      <%= select_tag 'recipients', recipients_options, multiple: true, class: 'form-control chosen-it form-msg', :data => {:placeholder => 'Para'}, required: true %>
    </div>
    <div class="form-group form-msg">

      <%= text_field_tag 'message[subject]', nil, class: 'form-control form-msg', required: true, placeholder:'Asunto' %>
    </div>
    <div class="form-group form-msg">
      <%= text_area_tag 'message[body]', nil, cols: 3, rows: 16, class: 'form-control form-msg', required: true %>
    </div>
    <%= submit_tag 'Enviar', class: 'btn btn-primary' %>
<% end %>

app/views/conversations/_show.html.erb
<div class="contenedor-responder">
  <div class="panel panel-default">
    <div class="panel-heading"><%= @conversation.subject %></div>

    <div class="panel-body">
      <div class="messages content" >
        <% @conversation.receipts_for(current_user).each do |receipt| %>
            <% message = receipt.message %>
            <%= image_tag message.sender.avatar.url, class: 'img-participant img-participant-first center-block' %>
            <%= link_to message.sender.name, profile_path(message.sender.name) %>
            <span>(<%= message.created_at.strftime('%-d %B %Y, %H:%M:%S') %>)</span><br>
            <%= message.body %>
            <hr>
        <% end %>
      </div>
    </div>
  </div>
  <%= form_tag reply_conversation_path(@conversation), method: :post, id: 'send-reply' do %>
      <div class="form-group content">
        <div class="textarea-wrapper">
          <%= text_area_tag 'body', nil, cols: 3, rows: 6, class: 'form-control', placeholder: 'Responder...', required: true %>
          <div class="textarea-clone"></div>
        </div>
      </div>
      <%= submit_tag 'Responder', class: 'btn btn-primary' %>
  <% end %>
</div>

<script>
    $(document).ready(function() {
//        $.mCustomScrollbar.defaults.scrollButtons.enable=true;
//        $.mCustomScrollbar.defaults.axis="y";
        $('.content').mCustomScrollbar({
            theme:"dark"
        });
        $("body").mCustomScrollbar({
            theme:"dark"
        });

    });
</script>

app/views/conversations/index.html.erb
<div class="container msg-container">
  <div class="row">
    <div class="col-sm-3 ">
      <ul class="nav nav-pills nav-stacked">
        <li><h3 class=" msg-title "><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> Mensajes</h3></li>
        <!--<li class="item-msg"><a href=""> Componer</a></li>-->
        <%= mailbox_section 'Componer', @box, '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>', :class=>'item-msg'  %>
        <%= mailbox_section 'Bandeja', @box, '<span class="glyphicon glyphicon-inbox" aria-hidden="true"></span>', :class=>'item-msg'  %>
        <%= mailbox_section 'Enviados', @box, '<span class="glyphicon glyphicon-send" aria-hidden="true"></span>', :class=>'item-msg'  %>
        <%= mailbox_section 'Papelera', @box, '<span class="glyphicon glyphicon-trash" aria-hidden="true"></span>', :class=>'item-msg'  %>
      </ul>
    </div>

    <div class="col-sm-9">
      <div class="container-mailbox">
        <% if @box == 'bandeja' %>
            <h3 class=" msg-title "><span class="glyphicon glyphicon-inbox" aria-hidden="true"></span> <%= @box.titleize %></h3>
        <% end %>
        <% if @box == 'enviados' %>
            <h3 class=" msg-title "><span class="glyphicon glyphicon-send" aria-hidden="true"></span> <%= @box.titleize %></h3>
        <% end %>
        <% if @box == 'papelera' %>
            <h3 class=" msg-title ">
              <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
              <%= @box.titleize %>
              <span class="empty-trash"><%= link_to 'Vaciar papelera', empty_trash_conversations_path, class: 'btn btn-danger', method: :delete, data: {confirm: 'Are you sure?'}%></span>
            </h3>
        <% end %>
        <% if @box == 'componer' %>
            <h3 class=" msg-title "><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= @box.titleize %></h3>
        <% end %>
        <% if @box != 'componer' %>
            <ul class="list-group">
              <%= render partial: 'conversations/conversation', collection: @conversations, :locals => {:@box=> @box} %>
            </ul>
        <% else %>
            <%= render 'form' %>
        <% end %>

        <div class="paginacion"><%= will_paginate(@conversations, :previous_label => 'Anterior', :next_label => 'Siguiente') %></div>
      </div>

      <div id="messages"></div>
    </div>

    <!--<div class="col-sm-3">-->
      <!--<div class="info-box">-->
        <!--<span class="info-box-icon bg-yellow"><i class="fa fa-envelope-o"></i></span>-->
        <!--<div class="info-box-content">-->
          <!--<span class="info-box-text">NUEVOS</span>-->
          <!--<span class="info-box-number"><%= current_user.mailbox.inbox({:read => false}).count %></span>-->
        <!--</div>&lt;!&ndash; /.info-box-content &ndash;&gt;-->
      <!--</div>-->
      <!--<div class="info-box">-->
        <!--<span class="info-box-icon bg-green"><i class="fa fa-inbox"></i></span>-->
        <!--<div class="info-box-content">-->
          <!--<span class="info-box-text">LEIDOS</span>-->
          <!--<span class="info-box-number">-->
            <!--<%= current_user.mailbox.inbox.count - current_user.mailbox.inbox({:read=>false}).count %>-->
          <!--</span>-->
        <!--</div>&lt;!&ndash; /.info-box-content &ndash;&gt;-->
      <!--</div>-->

      <!--<div class="info-box">-->
        <!--<span class="info-box-icon bg-aqua"><i class="fa fa-paper-plane-o"></i></span>-->
        <!--<div class="info-box-content">-->
          <!--<span class="info-box-text">ENVIADOS</span>-->
          <!--<span class="info-box-number"><%= current_user.mailbox.sentbox.count %></span>-->
        <!--</div>&lt;!&ndash; /.info-box-content &ndash;&gt;-->
      <!--</div>-->
      <!--<div class="info-box">-->
        <!--<span class="info-box-icon bg-red"><i class="fa fa-trash-o"></i></span>-->
        <!--<div class="info-box-content">-->
          <!--<span class="info-box-text">PAPELERA</span>-->
          <!--<span class="info-box-number"><%= current_user.mailbox.trash.count %></span>-->
        <!--</div>&lt;!&ndash; /.info-box-content &ndash;&gt;-->
      <!--</div>-->
    <!--</div>-->
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    $(document).ready(function(){
        $("#send-msg").on("ajax:complete", function(event,xhr,status){
            $('.form-msg').val('');
            $('#recipients').val('').trigger('chosen:updated');
        });
        $('.subject').click(function(){
            $('.container-mailbox').slideUp(300);
            $('#messages').slideDown();
        });

    });
</script>

app/views/conversations/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 contenedor-responder">
      <div class="panel panel-default">
        <div class="panel-heading"><%= @conversation.subject %></div>
        <div class="panel-body">
          <div class="messages content" >
            <% @conversation.receipts_for(current_user).each do |receipt| %>
                <% message = receipt.message %>
                <%= image_tag message.sender.avatar.url, class: 'img-participant img-participant-first center-block' %>
                <%= link_to message.sender.name, profile_path(message.sender.name) %>
                <span>(<%= message.created_at.strftime('%-d %B %Y, %H:%M:%S') %>)</span><br>
                <%= message.body %>
                <hr>
            <% end %>
          </div>
        </div>
      </div>
      <%= form_tag reply_conversation_path(@conversation), method: :post, id: 'send-reply' do %>
          <div class="form-group content">
            <div class="textarea-wrapper">
              <%= text_area_tag 'body', nil, cols: 3, rows: 6, class: 'form-control', placeholder: 'Responder...', required: true %>
              <div class="textarea-clone"></div>
            </div>
          </div>
          <%= submit_tag 'Responder', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
//        $.mCustomScrollbar.defaults.scrollButtons.enable=true;
//        $.mCustomScrollbar.defaults.axis="y";
        $('.content').mCustomScrollbar({
            theme:"dark"
        });
//        $("body").mCustomScrollbar({
//            theme:"dark"
//        });

    });
</script>

app/views/conversations/show.js.erb
$('<%= escape_javascript (render 'show') %>').appendTo('#messages');