config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope 'private' do
    resources :messages, only: [:index, :new, :create], :as => 'private_messages'
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :job_vacancies
  resources :applicants

  get '/search' => 'searches#search', as: :search
  get '/autocomplete/:query' => 'searches#autocomplete', as: :autocomplete

  get '/publications' => 'publications#index', as: :publications

  root 'users#home'
  post   '/sign_up'  => 'users#sign_up',  as: :sign_up
  post   '/sign_in'  => 'users#sign_in',  as: :sign_in
  delete '/sign_out' => 'users#sign_out', as: :sign_out
  get    '/:name'    => 'users#profile',  as: :profile
  post '/upload_photo' => 'users#upload_photo', as: :upload_photo
  post '/upload_cover' => 'users#upload_cover', as: :upload_cover

  post   '/new_post' => 'posts#create',   as: :new_post

  post   '/follow'   => 'relationships#create', as: :follow
  delete '/unfollow' => 'relationships#destroy', as: :unfollow

  resources :resumes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable
  has_one :resume
  searchkick autocomplete: ['name']

  has_attached_file :avatar,
                    # styles: { medium: '180x180>', thumb: '100x100>'},
                    default_url: '/images/:style/missing-avatar.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_attached_file :cover,
                     default_url: '/images/:style/missing-cover.jpg'
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/


  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'fan_id',
                                  dependent: :destroy
  has_many :idols, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'idol_id',
                                   dependent: :destroy
  has_many :fans, through: :passive_relationships

  has_many :job_vacancies


  has_secure_password

  #Seguir un usuario
  def follow(other_user)
    active_relationships.create(idol_id: other_user.id)
  end
  #Dejar de seguir a un usuario
  def unfollow(other_user)
    active_relationships.find_by(idol_id: other_user.id).destroy
  end
  #Retorna verdad si el usuario actual esta siguiendo a otro usuario
  def following?(other_user)
    idols.include?(other_user)
  end

  def feed
    following_ids = 'SELECT idol_id FROM relationships
                     WHERE  fan_id = :user_id'
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end


  def get_vacancies
    job_vacancies = Array.new
    all_job_vacancies = JobVacancy.all
    all_job_vacancies.each do |job_vacancy|
      unless self.resume.nil?
        unless self.resume.educations.nil?
          self.resume.educations.each do |education|
            if education.degree_name == job_vacancy.education
              job_vacancies.push(job_vacancy)
            end
          end
        end
      end
    end
    job_vacancies
  end

  def get_candidates
    candidates = Array.new
    self.job_vacancies.each do |vacancy|
      vacancy.applicants.each do|applicant|
        candidates.push(applicant)
      end
    end
    candidates
  end
  # METODOS PARA EL MAILBOXER
  def get_vacancies_applied
    Applicant.where(:applicant_id => self.id)
  end

  def mailboxer_email(object)
    self.email
  end
  def mailboxer_name
    self.name
  end

  def get_last_different_sender(conversation)
    if conversation.last_sender == self
      conversation.messages.reverse_each do |message|
        unless message.sender_id == self.id
          return User.find(message.sender_id)
        end
      end
    end
    conversation.last_sender
  end

  def number_of_active_participants(conversation)
    participants = Array.new
    conversation.messages.each do |message|
      participants.push(message.sender_id)
    end
    participants.uniq.count
  end

  # El ultimo en participar va primero, y no consideramos al current_user
  def active_participants(conversation)
    participants = Array.new
    conversation.messages.each do |message|
      participants.push(User.find(message.sender_id))
    end
    participants.reverse.uniq - [self]
  end
  #Obtenemos todos los mensajes, de todas las conversaciones que se encuentren sin leer
  def get_all_unread
    number = 0
    self.mailbox.inbox.each do |conversation|
      conversation.messages.each do |message|
        if message.is_unread?(self)
          number +=1
        end
      end
    end
    number
  end
  #Obtenemos todos los mensajes no leidos de una conversación
  def get_unread(conversation)
    number = 0
    conversation.messages.each do|message|
      if message.is_unread?(self)
        number += 1
      end
    end
    number
  end
  # def is_equal(user)
  #   if user == self
  #     return true
  #   end
  #   false
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home
    # render(:text => params)
  end

  def sign_up
    # render(:text => params)
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to profile_path(user.name)
    end
  end

  def sign_in
    # render(:text => params)
    user = User.find_by_email(params[:sesion][:email])
    if user && user.authenticate(params[:sesion][:password])
      login(user)
      redirect_to profile_path(user.name)
    else
      render :home
    end
  end

  def sign_out
    logout
    redirect_to root_path

  end

  def profile
    # render(:text => params)
    @user = User.find_by_name(params[:name])
    @posts = @user.posts
  end

  def upload_photo
    # render(:text => params)
    puts "aqui bota error"
    if current_user.update(user_params)
      redirect_to profile_path(current_user.name)
    end
  end
  def login
  end

  def upload_cover
    if current_user.update(user_params)
      redirect_to profile_path(current_user.name)
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar, :cover)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/users/home.html.erb
<div class="container home">

    <div class="row">
      <div class="col-md-4">
        <p class="welcome">CONECTADO CON UN MUNDO DE OPORTUNIDADES </p>
      </div>
      <div class="col-md-4"></div>
      <div class="col-md-3">
        <div class="formulario">
          <%= form_for :user, url: sign_up_path do |f| %>
              <div class="form-group">
                <%= f.text_field(:name, class: "form-control", placeholder: "Tu nombre") %>
              </div>
              <div class="form-group">
                <%= f.text_field(:email, class: "form-control", placeholder: "Email") %>
              </div>
              <div class="form-group">
                <%= f.password_field(:password, class: "form-control", placeholder: "Contraseña") %>
              </div>
              <div class="form-group">
                <%= f.password_field(:password_confirmation, class: "form-control", placeholder: "Confirmar contraseña") %>
              </div>

              <%= f.submit("Registrarse", class: "btn btn-primary") %>
          <% end %>

        </div>
        <div class="formulario formulario2">
          <%= form_for :sesion, url: sign_in_path do |f| %>
              <div class="form-group">
                <%= f.text_field(:email, class: "form-control", placeholder: "Email") %>
              </div>
              <div class="form-group">
                <%= f.password_field(:password, class: "form-control", placeholder: "Contraseña") %>
              </div>

              <%= f.submit('Iniciar sesion', class: "btn btn-primary") %>
          <% end %>

        </div>
      </div>
      <div class="col-md-1">

      </div>
    </div>
</div>

app/views/users/profile.html.erb
<div class="container-fluid" style="padding: 0px">
  <div id="container-cover">
    <div class="hovereffect">
      <%= image_tag current_user.cover.url, id: 'img-cover' %>
      <% if current_user.name == @user.name %>
          <div class="overlay">
            <h2>Actualizar foto de portada</h2>

            <%= form_for :user, url: upload_cover_path do |f| %>
                <label for="user_cover"><span class="glyphicon glyphicon-camera"></span></label>
                <%= f.file_field :cover,  class: 'inputfile', onchange: "this.form.submit();"%>
            <% end %>

          </div>
      <% end %>
    </div>
  </div>



</div>


<div id="container-avatar">
  <div class="hovereffect">
    <%= image_tag current_user.avatar.url, id: 'img-avatar' %>
    <% if current_user.name == @user.name %>
        <div class="overlay">
          <h2>Actualizar foto de perfil</h2>
          <%= form_for :user, url: upload_photo_path do |f| %>
              <label for="user_avatar"><span class="glyphicon glyphicon-camera"></span></label>
              <%= f.file_field :avatar, class: 'inputfile', onchange: "this.form.submit();" %>
          <% end %>
        </div>
    <% end %>
  </div>
</div>

<div class="container container-stat" style="clear: both">
  <div class="row">
    <div class="col-md-3" style="height: 45px"></div>
    <div class="col-md-2"><%= link_to "Publicaciones:#{@user.posts.count}","#" %></div>
    <div class="col-md-2"><%= link_to "Seguidores:#{@user.fans.count}","#" %></div>
    <div class="col-md-2"><%= link_to "Siguiendo:#{@user.idols.count}","#" %></div>
    <div class="col-md-3">
      <% if @user.name != current_user.name %>
          <% if current_user.following?(@user) %>
              <%= form_for :relationship, url: unfollow_path, html: {method: :delete} do |f| %>
                  <%= hidden_field_tag :idol_id, @user.id %>
                  <%= f.submit "Dejar de seguir", class: 'btn btn-primary' %>
              <% end %>
          <% else %>
              <%= form_for :relationship, url: follow_path do |f| %>
                  <%= hidden_field_tag :idol_id, @user.id %>
                  <%= f.submit "Seguir", class: 'btn btn-primary  btn-block' %>
              <% end %>
          <% end %>
      <% end %>
    </div>

  </div>
</div>





<div class="container">
<div class="row">
  <div class="col-md-3">
    <div class="contenedor-enlaces">
      <% if current_user.resume.nil? %>
        <%= link_to '<span class="glyphicon glyphicon-briefcase"></span> Crear Curriculum'.html_safe, new_resume_path ,class: 'enlaces-perfil'%>
      <% else %>
        <%= link_to '<span class="glyphicon glyphicon-pencil"></span> Editar Curriculum'.html_safe, resume_path(current_user.resume.id) ,class: 'enlaces-perfil'%>
      <% end %>
      <%= link_to '<span class="glyphicon glyphicon-tree-conifer"></span> Contratar'.html_safe, job_vacancies_path ,class: 'enlaces-perfil'%>
      <%= link_to '<span class="glyphicon glyphicon-picture"></span> Fotos'.html_safe, new_resume_path ,class: 'enlaces-perfil'%>

    </div>
  </div>
  <div class="col-md-6">
    <%= form_for :post, url: new_post_path do |f| %>
    <div class="row">
      <div class="col-md-12">
        <%= f.text_area(:body, class: "form-control", placeholder: 'How do you feel?', rows: 4) %>
      </div>
    </div>
    <div class="row barra-enviar">
      <div class="col-md-9 col-sm-8 col-xs-4">
        <label for="post_image">
            <span class="glyphicon glyphicon-camera btn btn-primary" aria-hidden="true"></span>
        </label>
        <%= f.file_field :image, class: 'inputfile' %>
      </div>
      <div class="col-md-3  col-sm-4  col-xs-8 cont-btn-publicar">
        <button type="submit" class="btn btn-primary">
          Publicar <span class="glyphicon glyphicon-bullhorn" aria-hidden="true"></span>
        </button>
      </div>
    </div>
    <% end %>
    <%=@user%>
    <%=@posts.size%>
    <% @posts.each do |post| %>
        <div class="container-body ">
          <%= image_tag @user.avatar.url, id: 'img-avatar' %>
          <h5><%= post.user.name %></h5>
          <%= image_tag post.pictures.first.image.url, class: 'img-post' %>
          <p class="format-text"><%= post.body %></p>
          <button type="button" class="btn btn-default" aria-label="Left Align">
            <span class=" glyphicon glyphicon-thumbs-up" aria-hidden="true"></span>
          </button>
          <button type="button" class="btn btn-default" aria-label="Left Align">
            <span class=" glyphicon glyphicon-thumbs-down" aria-hidden="true"></span>
          </button>
          <button type="button" class="btn btn-default" aria-label="Left Align">
            <span class=" glyphicon glyphicon-share-alt" aria-hidden="true"></span>
          </button>
        </div>
    <% end %>
  </div>
  <div class="col-md-3 col-derecha">
    <div class="row text-center">
      <div class="texto-sugerencias">SUGERENCIAS</div>
    </div>
    <div class="row contenedor-sugerencia">
        <div class="col-md-4">
          <%= image_tag User.find_by(:id=>1).avatar.url, class: 'img-circle img-sugerencia' %>
        </div>
        <div class="col-md-8">
          <p>Franz Osvaldo Beltran Mercado</p>
          <!--<button class="btn btn-primary">Seguir</button>-->
          <button style="font-size:12px" class="btn  btn-primary">Seguir <i class="fa fa-user-plus"></i></button>
        </div>
    </div>
    <div class="row contenedor-sugerencia">
      <div class="col-md-4">
        <%= image_tag User.find_by(:id=>2).avatar.url, class: 'img-circle img-sugerencia' %>
      </div>
      <div class="col-md-8">
        <p>Andrea Maria Alvarado Penarrieta</p>
        <!--<button class="btn btn-primary">Seguir</button>-->
        <button style="font-size:12px" class="btn  btn-primary">Seguir <i class="fa fa-user-plus"></i></button>
      </div>
    </div>

  </div>
</div>




</div>