config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  scope 'private' do
    resources :messages, only: [:index, :new, :create], :as => 'private_messages'
  end
  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
    end
    collection do
      delete :empty_trash
    end
  end

  resources :job_vacancies
  resources :applicants

  get '/search' => 'searches#search', as: :search
  get '/autocomplete/:query' => 'searches#autocomplete', as: :autocomplete

  get '/publications' => 'publications#index', as: :publications

  root 'users#home'
  post   '/sign_up'  => 'users#sign_up',  as: :sign_up
  post   '/sign_in'  => 'users#sign_in',  as: :sign_in
  delete '/sign_out' => 'users#sign_out', as: :sign_out
  get    '/:name'    => 'users#profile',  as: :profile
  post '/upload_photo' => 'users#upload_photo', as: :upload_photo
  post '/upload_cover' => 'users#upload_cover', as: :upload_cover

  post   '/new_post' => 'posts#create',   as: :new_post

  post   '/follow'   => 'relationships#create', as: :follow
  delete '/unfollow' => 'relationships#destroy', as: :unfollow

  resources :resumes

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  belongs_to :job_vacancy
  def self.not_applied?(job_vacancy_id, current_user_id)
    Applicant.where(:job_vacancy_id => job_vacancy_id, :applicant_id => current_user_id).empty?
  end

  def applicant_name
    User.find(applicant_id).name
  end

  def applicant_resume_id
    User.find(applicant_id).resume.id
  end
end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :resume
end

app/models/email.rb
class Email < ActiveRecord::Base
  belongs_to :resume
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  belongs_to :resume
end

app/models/job_vacancy.rb
class JobVacancy < ActiveRecord::Base
  belongs_to :user
  has_many :applicants
end

app/models/phone.rb
class Phone < ActiveRecord::Base
  belongs_to :resume
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :resume
  has_attached_file :photo,
                    styles: { resume: "300x300>" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :post
  has_attached_file :image,
                    styles: { medium: "300x300>", thumb: "100x100>" },
                    default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image,
                                    content_type: /\Aimage\/.*\Z/
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  default_scope -> {order(created_at: :desc)}
  has_many :pictures
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :idol, class_name: 'User'
  belongs_to :fan, class_name: 'User'
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  belongs_to :user
  has_many :photos
  has_many :emails
  has_many :phones
  has_many :sites
  has_many :experiences
  has_many :educations
  accepts_nested_attributes_for :photos, reject_if: lambda {|attributes| attributes['photo'].blank?}
  accepts_nested_attributes_for :emails, reject_if: lambda {|attributes| attributes['email'].blank?}
  accepts_nested_attributes_for :phones, reject_if: lambda {|attributes| attributes['number'].blank?}
  accepts_nested_attributes_for :sites, reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :experiences, reject_if: :all_blank
  accepts_nested_attributes_for :educations, reject_if: :all_blank
end

app/models/site.rb
class Site < ActiveRecord::Base
  belongs_to :resume
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  acts_as_messageable
  has_one :resume
  searchkick autocomplete: ['name']

  has_attached_file :avatar,
                    # styles: { medium: '180x180>', thumb: '100x100>'},
                    default_url: '/images/:style/missing-avatar.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_attached_file :cover,
                     default_url: '/images/:style/missing-cover.jpg'
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/


  has_many :posts, dependent: :destroy

  has_many :active_relationships, class_name: 'Relationship',
                                  foreign_key: 'fan_id',
                                  dependent: :destroy
  has_many :idols, through: :active_relationships

  has_many :passive_relationships, class_name: 'Relationship',
                                   foreign_key: 'idol_id',
                                   dependent: :destroy
  has_many :fans, through: :passive_relationships

  has_many :job_vacancies


  has_secure_password

  #Seguir un usuario
  def follow(other_user)
    active_relationships.create(idol_id: other_user.id)
  end
  #Dejar de seguir a un usuario
  def unfollow(other_user)
    active_relationships.find_by(idol_id: other_user.id).destroy
  end
  #Retorna verdad si el usuario actual esta siguiendo a otro usuario
  def following?(other_user)
    idols.include?(other_user)
  end

  def feed
    following_ids = 'SELECT idol_id FROM relationships
                     WHERE  fan_id = :user_id'
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end


  def get_vacancies
    job_vacancies = Array.new
    all_job_vacancies = JobVacancy.all
    all_job_vacancies.each do |job_vacancy|
      unless self.resume.nil?
        unless self.resume.educations.nil?
          self.resume.educations.each do |education|
            if education.degree_name == job_vacancy.education
              job_vacancies.push(job_vacancy)
            end
          end
        end
      end
    end
    job_vacancies
  end

  def get_candidates
    candidates = Array.new
    self.job_vacancies.each do |vacancy|
      vacancy.applicants.each do|applicant|
        candidates.push(applicant)
      end
    end
    candidates
  end
  # METODOS PARA EL MAILBOXER
  def get_vacancies_applied
    Applicant.where(:applicant_id => self.id)
  end

  def mailboxer_email(object)
    self.email
  end
  def mailboxer_name
    self.name
  end

  def get_last_different_sender(conversation)
    if conversation.last_sender == self
      conversation.messages.reverse_each do |message|
        unless message.sender_id == self.id
          return User.find(message.sender_id)
        end
      end
    end
    conversation.last_sender
  end

  def number_of_active_participants(conversation)
    participants = Array.new
    conversation.messages.each do |message|
      participants.push(message.sender_id)
    end
    participants.uniq.count
  end

  # El ultimo en participar va primero, y no consideramos al current_user
  def active_participants(conversation)
    participants = Array.new
    conversation.messages.each do |message|
      participants.push(User.find(message.sender_id))
    end
    participants.reverse.uniq - [self]
  end
  #Obtenemos todos los mensajes, de todas las conversaciones que se encuentren sin leer
  def get_all_unread
    number = 0
    self.mailbox.inbox.each do |conversation|
      conversation.messages.each do |message|
        if message.is_unread?(self)
          number +=1
        end
      end
    end
    number
  end
  #Obtenemos todos los mensajes no leidos de una conversación
  def get_unread(conversation)
    number = 0
    conversation.messages.each do|message|
      if message.is_unread?(self)
        number += 1
      end
    end
    number
  end
  # def is_equal(user)
  #   if user == self
  #     return true
  #   end
  #   false
  # end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def recipients_options
    s = ''
    User.all.each do |user|
      s << "<option value='#{user.id}'>#{user.name}</option>"
    end
    s.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(:id => session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end
end

app/views/layouts/_top_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'UCB', publications_path, class: 'navbar-brand' %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "#{current_user.name}", profile_path(current_user.name) %></li>
        <li><%= link_to 'Publicaciones', publications_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Ofertas <span class="badge"><%= current_user.get_vacancies.count - current_user.get_vacancies_applied.count%></span></a>
          <ul class="dropdown-menu">
            <% current_user.get_vacancies.each do |vacancy| %>
                <% if Applicant.not_applied?(vacancy.id, current_user.id) %>
                    <li><%= link_to User.find(vacancy.user_id).name , job_vacancy_path(vacancy.id) %></li>
                <% end %>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="">Todos las ofertas</a></li>

          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Postulantes <span class="badge"><%= current_user.get_candidates.count %></span></a>
          <ul class="dropdown-menu">
            <% current_user.get_candidates.each do |candidate| %>
                <li><%= link_to candidate.applicant_name, resume_path(candidate.applicant_resume_id), :class =>'link-postulante' %></li>
            <% end %>
            <li role="separator" class="divider"></li>
            <li><a href="">Todos los postulantes</a></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <span class="badge badge-notify inbox-notify"><%= current_user.get_all_unread %></span></a>
          <ul class="dropdown-menu">
            <div class=" dropdown-menu-inbox content">
              <% current_user.mailbox.inbox.each do |conversation| %>
                  <% if conversation.is_unread?(current_user) %>
                      <li>
                        <% if current_user.active_participants(conversation).count == 1 %>
                            <%= link_to conversation_path(conversation) do %>
                                <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
                                <%= current_user.active_participants(conversation)[0].name %>
                                (<%= conversation.created_at.strftime('%-d %B %Y') %>)
                                <span class="badge badge-notify inbox-notify"><%= current_user.get_unread(conversation) %></span>
                            <% end %>
                        <% end %>
                        <% if current_user.active_participants(conversation).count == 2 %>
                            <%= link_to conversation_path(conversation) do %>
                                <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
                                <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
                                <%= current_user.active_participants(conversation)[0].name %>,
                                <%= current_user.active_participants(conversation)[1].name %>
                                (<%= conversation.created_at.strftime('%-d %B %Y') %>)
                                <span class="badge badge-notify inbox-notify"><%= current_user.get_unread(conversation) %></span>
                            <% end %>
                        <% end %>
                        <% if current_user.active_participants(conversation).count == 3 %>
                            <%= link_to conversation_path(conversation) do %>
                                <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
                                <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
                                <%= image_tag current_user.active_participants(conversation)[2].avatar.url, class: 'img-participant img-participant-third center-block' %>
                                <%= current_user.active_participants(conversation)[0].name %>,
                                <%= current_user.active_participants(conversation)[1].name %>,
                                <%= current_user.active_participants(conversation)[2].name %>
                                (<%= conversation.created_at.strftime('%-d %B %Y') %>)
                                <span class="badge badge-notify inbox-notify"><%= current_user.get_unread(conversation) %></span>
                            <% end %>
                        <% end %>
                        <% if current_user.active_participants(conversation).count > 3 %>
                            <%= link_to conversation_path(conversation) do %>
                                <%= image_tag current_user.active_participants(conversation)[0].avatar.url, class: 'img-participant img-participant-first center-block' %>
                                <%= image_tag current_user.active_participants(conversation)[1].avatar.url, class: 'img-participant img-participant-second center-block' %>
                                <span class="img-participant-others">+<%= current_user.active_participants(conversation).count-2 %></span>
                                <%= current_user.active_participants(conversation)[0].name %>,
                                <%= current_user.active_participants(conversation)[1].name %>,
                                Otros
                                (<%= conversation.created_at.strftime('%-d %B %Y') %>)
                                <span class="badge badge-notify inbox-notify"><%= current_user.get_unread(conversation) %></span>
                            <% end %>
                        <% end %>
                      </li>
                  <% end %>
              <% end %>
            </div>
            <li role="separator" class="divider"></li>
            <li class="ver-todos"><%= link_to 'Ver Todos', conversations_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle prueba" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"><%= image_tag current_user.avatar.url, class: 'img-navbar' %> Franz Beltran</a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Terminar sesión', sign_out_path, method: :delete %></li>
          </ul>
        </li>

      </ul>

      <%= form_tag search_path, id: 'formulario', class: 'navbar-form navbar-left', method: :get do %>
          <div class="form-group">
            <%= text_field_tag :query, params[:query],  class: 'form-control typeahead', placeholder: 'Buscar...'%>
          </div>
          <!--<%= submit_tag 'Search', class: 'btn btn-primary' %>-->

      <% end %>
    </div>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teresa</title>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= render partial: 'layouts/top_navbar' %>
<% end %>
<%= yield %>
</body>
</html>

<script>
    var people = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value'),
        queryTokenizer: Bloodhound.tokenizers.whitespace,

        remote: {
            url: '../autocomplete/%QUERY',
            wildcard: '%QUERY'

        }
    });

    $('.typeahead').typeahead(null, {
        name: 'people',
        display: 'name',
        source: people.ttAdapter()
    }).on('typeahead:selected', function () {
        console.log('selecionado');
//        alert('franz');
        document.getElementById("formulario").submit();
    });
//    $('.content').mCustomScrollbar({
//      theme:"dark"
//    });
//    $("body").mCustomScrollbar({
//      theme:"dark"
//    });

</script>